<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netcoreapp3.1;net5;net6;net7;net8;net9;net10.0;</TargetFrameworks>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageId>Acme.EFCore.Small</PackageId>
		<!--
				后缀语义
				-alpha：Alpha 版本，通常用于在制品和试验品。
				-beta：Beta 版本，通常指可用于下一计划版本的功能完整的版本，但可能包含已知 bug。
				-rc：候选发布，通常可能为最终（稳定）版本，除非出现重大 bug。
		-->
		<Version>2.0.0.2 -alpha</Version>
		<Authors>yzxs</Authors>
		<Company>yzxs</Company>
		<Product>Acme.EFCore.Small</Product>
		<Copyright>yzxs</Copyright>
		<AssemblyName>Acme.EFCore.Small</AssemblyName>
		<RootNamespace>Acme.EFCore.Small</RootNamespace>
		<Description>轻量级EFCore操作类库</Description>
		<Title>Acme.EFCore.Small</Title>
		<PackageTags>Acme;EntityFrameworkCore;EF;EFCore;EFCore.Small;yzxs;core3.1;net5;net6;net7;net8;net9;net10;云中小生;Framework;Entity;EF类库;</PackageTags>
		<PackageProjectUrl>https://www.nuget.org/packages/Acme.EFCore.Small/2.0.0.2-alpha#readme-body-tab</PackageProjectUrl>
		<PackageReleaseNotes>
			<!--1.分离提交和事务到工作单元中（和老版本有较大差异，该版本还未全面测试，请谨慎使用到生产环境）-->
			1.更新.NET10依赖包版本，Microsoft.EntityFrameworkCore 版本为 Version10.0.5 到 Version10.0.6
			2.修复已知bug……
		</PackageReleaseNotes>
		<PackageReadmeFile>readme.md</PackageReadmeFile>
		<NoWarn>IDE0305;IDE0300;IDE0290;</NoWarn>
	</PropertyGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp3.1'">
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.32" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net5'">
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.17" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net6'">
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.20" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net7' ">
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.20" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net8' ">
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net9' ">
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0' ">
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.6" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="NuGet.Build.Tasks.Pack" Version="6.14.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<None Include="readme.md" Pack="true" PackagePath="\" />
		<None Include="readme.en.md" Pack="true" PackagePath="\" />
	</ItemGroup>
</Project>