<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net6;net7;net8</TargetFrameworks>
		<Nullable>enable</Nullable>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageId>Acme.EFCore.Small</PackageId>
		<!--
				后缀语义
				-alpha：Alpha 版本，通常用于在制品和试验品。
				-beta：Beta 版本，通常指可用于下一计划版本的功能完整的版本，但可能包含已知 bug。
				-rc：候选发布，通常可能为最终（稳定）版本，除非出现重大 bug。
		-->
		<Version>1.2.6</Version>
		<Authors>yzxs</Authors>
		<Company>yzxs</Company>
		<Product>Acme.EFCore.Small</Product>
		<Copyright>yzxs</Copyright>
		<AssemblyName>Acme.EFCore.Small</AssemblyName>
		<RootNamespace>Acme.EFCore.Small</RootNamespace>
		<Description>轻量级EFCore通用类库</Description>
		<Title>Acme.EFCore.Small</Title>
		<PackageTags>Acme;EntityFrameworkCore;EF;EFCore;EFCore.Small;yzxs;云中小生;net6;net7;net8</PackageTags>
		<PackageProjectUrl>https://www.nuget.org/packages/Acme.EFCore.Small/1.2.5.5#readme-body-tab</PackageProjectUrl>
		<PackageReleaseNotes>
			<!--.NET6、.NET7的EFCore版本升级到7.0.20，.NET8的EFCore版本升级到8.0.6-->
			.NET8的EFCore版本升级到8.0.8
		</PackageReleaseNotes>
		<PackageReadmeFile>readme.md</PackageReadmeFile>
	</PropertyGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net6'">
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.20" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net7' ">
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.20" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net8' ">
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="NuGet.Build.Tasks.Pack" Version="6.11.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<None Include="readme.md" Pack="true" PackagePath="\" />
	</ItemGroup>
</Project>