<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net6;net7;net8;net9;</TargetFrameworks>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageId>Acme.EFCore.Small</PackageId>
		<!--
				后缀语义
				-alpha：Alpha 版本，通常用于在制品和试验品。
				-beta：Beta 版本，通常指可用于下一计划版本的功能完整的版本，但可能包含已知 bug。
				-rc：候选发布，通常可能为最终（稳定）版本，除非出现重大 bug。
		-->
		<Version>1.2.8.1</Version>
		<Authors>yzxs</Authors>
		<Company>yzxs</Company>
		<Product>Acme.EFCore.Small</Product>
		<Copyright>yzxs</Copyright>
		<AssemblyName>Acme.EFCore.Small</AssemblyName>
		<RootNamespace>Acme.EFCore.Small</RootNamespace>
		<Description>Lightweight EFCore Universal Library</Description>
		<Title>Acme.EFCore.Small</Title>
		<PackageTags>Acme;EntityFrameworkCore;EF;EFCore;EFCore.Small;yzxs;net6;net7;net8;net9;</PackageTags>
		<PackageProjectUrl>https://www.nuget.org/packages/Acme.EFCore.Small/1.2.5.5#readme-body-tab</PackageProjectUrl>
		<PackageReleaseNotes>
			Change English annotations
			<!--更新.NET8 EntityFrameworkCore版本为8.0.10-->
		</PackageReleaseNotes>
		<PackageReadmeFile>readme.md</PackageReadmeFile>
	</PropertyGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net6'">
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.20" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net7' ">
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.20" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net8' ">
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net9' ">
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="NuGet.Build.Tasks.Pack" Version="6.12.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<None Include="readme.md" Pack="true" PackagePath="\" />
	</ItemGroup>
</Project>