<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>netcoreapp3.1;net5;</TargetFrameworks>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageId>Acme.EFCore.Small</PackageId>
		<Version>1.0.4</Version>
		<Authors>yzxs</Authors>
		<Company>yzxs</Company>
		<Product>Acme.EFCore.Small</Product>
		<Copyright>yzxs</Copyright>
		<PackageIcon></PackageIcon>
		<AssemblyName>Acme.EFCore.Small</AssemblyName>
		<RootNamespace>Acme.EFCore.Small</RootNamespace>
		<Description>轻量级EFCore通用类库</Description>
		<Title>Acme.EFCore.Small</Title>
		<PackageTags>Acme;EntityFrameworkCore;EF;EFCore;EFCore.Small;yzxs;云中小生;netcoreapp3.1</PackageTags>
		<PackageProjectUrl>https://www.nuget.org/packages/Acme.EFCore.Small/</PackageProjectUrl>
		<PackageReleaseNotes>
			修复已知bug（技术支持联系邮箱：yzxs949@163.com）
		</PackageReleaseNotes>
	</PropertyGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp3.1'">
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.32" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net5'">
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.17" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="NuGet.Build.Tasks.Pack" Version="6.9.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>
