<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8;net9;</TargetFrameworks>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageId>Acme.EFCore</PackageId>
		<Version>3.3.6</Version>
		<Authors>yzxs</Authors>
		<Company>yzxs</Company>
		<Product>Acme.EFCore</Product>
		<Copyright>yzxs</Copyright>
		<AssemblyName>Acme.EFCore</AssemblyName>
		<RootNamespace>Acme.EFCore</RootNamespace>
		<Description>Lightweight EFCore Universal Library</Description>
		<Title>Acme.EFCore</Title>
		<PackageTags>Acme;EntityFrameworkCore;EF;EFCore;EFCore;yzxs;net8;net9;</PackageTags>
		<PackageReleaseNotes>
			A brand new version of Acme EFCore
		</PackageReleaseNotes>
		<PackageProjectUrl>https://www.nuget.org/packages/Acme.EFCore/3.3.6#readme-body-tab</PackageProjectUrl>
	</PropertyGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net8' ">
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.4" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net9' ">
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.4" />
	</ItemGroup>
	<ItemGroup>
	  <None Remove="readme.md" />
	</ItemGroup>
	<ItemGroup>
	  <EmbeddedResource Include="readme.md">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="NuGet.Build.Tasks.Pack" Version="6.12.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>
